version: "3.3"
services:
  proxy:
    image: proxy
    build:
        context: .
        dockerfile: Dockerfile.nginx
    restart: unless-stopped
    volumes:
      - ./:/var/www/html
      - ./etc/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 7777:80
    dns:
      - 8.8.8.8
    networks:
      - main

  app:
    image: service-php-7.4
    build: .
    restart: unless-stopped
    volumes:
      - .:/var/www/html:delegated
      - ./etc/php/php.ini:/usr/local/etc/php/php.ini:delegated
    entrypoint: "php-fpm -F -O"
    working_dir: /var/www/html
    dns:
      - 8.8.8.8
    networks:
      - main

  postgres:
    image: postgres:13.4
    restart: always
    environment:
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=ngojeg
      - TZ=Asia/Jakarta
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5433:5432'
    volumes:
      - ./etc/postgres-data:/var/lib/postgresql/data
    networks:
      - main

networks:
  main:
    driver: bridge
