FROM nginx:latest
LABEL maintainer "surahman325@gmail.com"


COPY . /tmp/app

RUN set -x \
    && cp -rf /tmp/app/etc/nginx/conf.d/default.conf /etc/nginx/conf.d/default.conf \
    && mkdir -p /var/www/html \
    && cp -rf /tmp/app/* /var/www/html/

